### PR TITLE
Added sql query check for conforming values between multiple dimensions.

### PR DESCRIPTION
**Pull request by varunmittal91**
This pr enable sql based checks that allow more free logic when comparing against multiple dimensions.

The only requirement is that it should create an alias with name output_check which should be of type boolean and the table
name should be df as it will substituted by the execution engine.

A sample query would look like

                    SELECT
                        test_dimension,
                        CASE WHEN test_dimension = 'some-value' THEN true ELSE false END AS check_output
                        FROM df;

### CODE REVIEW

**Review by mike-finopsorg — APPROVED** [review]

**Review by joshk0 — APPROVED** [review]
cool, i can try this on the 1.0 rules!

**Comment by joshk0** [comment]
I haven't been able to get it to work with this:

```
column_id: SkuPriceId
check_friendly_name: SkuPriceId must be set for certain values of ChargeType
check:
  sql_query: |
    SELECT CASE
        WHEN ChargeType IN ('Purchase', 'Usage', 'Refund') AND SkuPriceId IS NULL THEN TRUE
        ELSE FALSE
    END AS check_output
    FROM df;
```

anything obvious here?

It seems to pass, even though I force it to return FALSE, or i throw an exception in `check_sql_query`. It somehow looks like the new code path is not being launched at all.

**Comment by varunmittal91** [comment]
> I haven't been able to get it to work with this:
> 
> ```
> column_id: SkuPriceId
> check_friendly_name: SkuPriceId must be set for certain values of ChargeType
> check:
>   sql_query: |
>     SELECT CASE
>         WHEN ChargeType IN ('Purchase', 'Usage', 'Refund') AND SkuPriceId IS NULL THEN FALSE
>         ELSE TRUE
>     END AS check_output
>     FROM df;
> ```
> 
> anything obvious here?
> 
> It seems to pass, even though I force it to return FALSE, or i throw an exception in `check_sql_query`. It somehow looks like the new code path is not being launched at all.



> I haven't been able to get it to work with this:
> 
> ```
> column_id: SkuPriceId
> check_friendly_name: SkuPriceId must be set for certain values of ChargeType
> check:
>   sql_query: |
>     SELECT CASE
>         WHEN ChargeType IN ('Purchase', 'Usage', 'Refund') AND SkuPriceId IS NULL THEN FALSE
>         ELSE TRUE
>     END AS check_output
>     FROM df;
> ```
> 
> anything obvious here?
> 
> It seems to pass, even though I force it to return FALSE, or i throw an exception in `check_sql_query`. It somehow looks like the new code path is not being launched at all.

It should have trigger, syntax wise looks correct. I am trying this on my computer to double check.

**Comment by varunmittal91** [comment]
Merged together with https://github.com/finopsfoundation/focus_validator/pull/102.

**Pull request closed without merging**
